name: Build & Push to Docker Hub

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build-and-push:
    # لو عايزة تحميه يشتغل بس على ريبو/فوركك، استخدمي اسمك نصيًا:
    # if: ${{ github.repository_owner == 'fatmahmed' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/java-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # فعّليه لو Dockerfile مش multi-stage وعايزة jar قبل البناء
      # - name: Build JAR
      #   run: ./mvnw -q -DskipTests package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=raw,value=latest

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}